<!DOCTYPE html>
<html lang="en" dir="rtl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="assets/lib/normalize.css">
    <link rel="stylesheet" href="assets/fonts/font_cairo.css">
    <link rel="stylesheet" href="assets/lib/splide.min.css">
    <link rel="stylesheet" href="assets/css/main.css">
</head>

<body>


    <nav>
        <?php include($config['COMPONENT_PATH'] . DS . 'NavbarComponent.php') ?>
    </nav>

    <div class="orphans section">
        <img class="orphans-hero" src="<?= $project['hero'] ?>" alt="">
        <div class="container">

            <form class="card orphans-form">
                <div class="orphans-header">كفالة يتيم</div>
                <input type="text" class="input-text">
                <div class="orphans-row">
                    <input type="text" class="input-text">
                    <select name="" id="" class="input-text">
                        <option value=""></option>
                    </select>
                </div>
                <button class="form-button">اكفلني</button>
            </form>
        </div>

        <img class="orphans-logo" src="" alt="">
    </div>
    <div class="orphans-search">
        <div class="container">
        <?php include($config['COMPONENT_PATH'] . 'Forms' . DS . 'FormOrphanComponent.php') ?>
        </div>

    </div>
    <div class="orphans-cards">
        <div class="container">
            <div class="list-cards">
                <?php include($config['COMPONENT_PATH'] . 'Cards' . DS . 'CardOrphanComponent.php') ?>
                <?php include($config['COMPONENT_PATH'] . 'Cards' . DS . 'CardOrphanComponent.php') ?>
                <?php include($config['COMPONENT_PATH'] . 'Cards' . DS . 'CardOrphanComponent.php') ?>
            </div>
        </div>
    </div>
    <footer>
        <div class="container">
            <?php include($config['COMPONENT_PATH'] . DS . 'FooterComponent.php') ?>
        </div>
    </footer>
    <?php include($config['COMPONENT_PATH'] . DS . 'Modals' . DS . 'ModalComponent.php') ?>
    <script src="assets/lib/splide.min.js"></script>
    <script src="assets/script/main.js"></script>





</body>

</html>